### ISSUE TITLE
Error while compiling main sources

### ISSUE THREAD

**Issue by billpcs** [kjellwinblad/ScalaEdit#1]
I got this error while trying to install the ScalaEdit. Hope it helps.

[info] Compiling main sources...
[error] path/to/ScalaEdit/src/main/scala/me/winsh/scalaedit/gui/console/SBTConsoleWithErrorList.scala:147: type mismatch;
[error]  found   : javax.swing.JList
[error]  required: java.awt.Component
[error]           popupMenu.show(peer, me.getX(), me.getY());
[error]                          ^
[error] one error found

**Comment by kjellwinblad** [comment]
Which java version are you using?

**Comment by billpcs** [comment]
On windows:
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

On Ubuntu:
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Checked it on both Windows and Ubuntu , same error.

**Comment by billpcs** [comment]
Ten years? Time flies by... Closing
